[project]
name = 'HoloChain'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.holo-marketplace]
path = 'contracts/holo-marketplace.clar'
clarity_version = 2
epoch = 2.5

[contracts.holo-nft]
path = 'contracts/holo-nft.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
